services:
  db:
    container_name: tasks-list
    hostname: postgres
    image: "postgres:13"
    environment:
      POSTGRES_DB: tasks_app
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_tasks:/var/lib/postgres

volumes:
  db_tasks:
