services:
  db:
    container_name: tasks-list
    hostname: postgres
    image: "postgres:13"
    env_file:
      - .env_example
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_tasks:/var/lib/postgres

volumes:
  db_tasks:
