services:
  db:
    container_name: tasks-list
    hostname: postgres
    image: "postgres:13"
    env_file:
      - .env_example
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_tasks:/var/lib/postgres

  tasks-app-be:
    container_name: tasks-app-be
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env_example
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
    command: npm run dev:init

volumes:
  db_tasks:
